version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts # the primary container, where your job's commands are run
    steps:
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - checkout
      - run: npm install
      - run: npm run lint
      - save_cache:
          paths:
              - ~/usr/local/lib/node_modules  # location depends on npm version
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
