version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts # the primary container, where your job's commands are run
    steps:
      - add_ssh_keys:
          fingerprints:
              = "da:9b:86:50:c7:25:f0:f8:62:b7:82:dd:d4:97:24:d2"
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run: npm install
      - run: npm run lint
      - save_cache:
          paths:
              - ~/usr/local/lib/node_modules  # location depends on npm version
          key: v1-npm-deps-{{ checksum "package-lock.json" }}

      - setup_remote_docker
      - run: docker build -t root_japanese-admin-api:latest .
      - run: docker save -o ./japanese-admin-api.tar root_japanese-admin-api:latest
      - run: scp ./japanese-admin-api.tar root@oskarlindgren.se:/root/japanese-admin-api.tar
      - run: ssh -o StrictHostKeyChecking=no root@oskarlindgren.se "/bin/bash docker load -i ./japanese-admin-api.tar"
      #- run: docker -H "ssh://root@oskarlindgren.se" ps
      #- run: docker -H "ssh://root@oskarlindgren.se" load -i ./japanese-admin-api.tar
